#[[sweep]]
#path="capillary.interface_thickness"
#values=[0.1, 0.01, 0.001]
#
#[[sweep]]
#path="capillary.contact_angle_degree"
#values=[0, 60, 75, 90, 105, 120, 180]

[grid]
pixel_size = 0.01
nb_pixels = 256

[capillary]
interface_thickness = 0.01
contact_angle_degree = 0
perimeter_weight = 1.0

[trajectory]
min_separation = 0.2
max_separation = 0.4
step_size = 0.01
round_trip = true

[optimizer]
max_nb_iters = 500
max_nb_loops = 30
tol_gradient = 1e-6
tol_eq_constraint = 1e-6

[constraint]
liquid_volume_percent = 50.0
