name: lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[lint]"

      - name: Lint with ruff
        run: |
          # Block if the code is not formatted. Run `ruff format .` to fix.
          ruff format --check .
          # Block if linting against rules selected in pyproject.toml fails.
          ruff check --statistics .
          # Advisory only: complexity 10.
          ruff check --exit-zero --select=C901 --config "lint.mccabe.max-complexity=10" .
